### ISSUE TITLE
Investigate the possibility of providing an OSX package

### ISSUE THREAD

**Issue by ei8fdb** [nogoegst/onionize#50]
Hi!

How difficult would it be to provide users with an application (I guess a .app)?

I've got an OS X machine and would be happy to do some testing.

**Comment by unkaktus** [comment]
Hi!
I actually tried to do this. I stopped at packaging it to an .app because of complicated GTK3+ shared library stuff. I don't have a macOS running on my computers. So maybe there is someone who is familiar with all this xcode tooling can help? I bet packaging can be even done on another platform, that would be absolutely great.

**Comment by unkaktus** [comment]
closing this in favor of #63, as it is going to become easily portable.
