### ISSUE TITLE
Wish: Filesharing & instant messaging with Ricochet :)

### ISSUE THREAD

**Issue by ei8fdb** [nogoegst/onionize#52]
Hi! 

I'm not sure if you're familiar with [Ricochet](https://github.com/ricochet-im/). It'd be really nice if Onionize and Ricochet could make an offspring - p2p IM and p2p file sharing. 💯  😈

**Comment by unkaktus** [comment]
Hi!

Actually... I started implementing this very idea long time ago as tulp.(https://github.com/nogoegst/tulp). Basically it serves a web interface via onion service so a client can chat over OTR with tulp instance. Yes , it is very similar to onionize :wink:

That project is somehow abandoned by me because... I have no idea why. I should probably revive it someday. btw, it was left kind of usable (though with cli only) so PRs or anything are much appreciated!

I will close this as I feel it to be addressed by tulp in a way.
Thank you for sharing your thoughts!
