### ISSUE TITLE
Provide cancellation of process at any moment

### ISSUE THREAD

**Issue by unkaktus** [nogoegst/onionize#59]
Right now if uses clicks on "start sharing" button they are unable to cancel it while it says "starting sharing...". Due to technical limitations there is 30s delay before onion service goes live, so the user may want to cancel process right at this point.

**Comment by ei8fdb** [comment]
This 30 second delay is due to the Tor service, right? Is there anyway that the process could be something like this:

- user goes through "create share" process
- user presses "start share" button
- Onionize tells Tor process to create Onion service
- During this time, UI shows "transition state" "please wait....creating Onion share....tick..tock..tick..tock"

- if the user wants to stop the share being created, they are able to press a button, and Onionize kills the Tor process, and "resets" it somehow? This stops the share being made?

If there's not an easy way for it to happen - let's think about the implications of the user *not* being able to stop the share being created:

- the user *did* want the share to be created, but they've then change their minds
- until the user makes the onion service URL public, then no-one knows it exists, right?

Maybe you could make an argument that "someone nasty" could scan for Onion URLs.

But if the user wants to "stop" sharing, then they are able to do it (once live).

Stopping the sharing would be achieved by pressing Stop share, after the 30 seconds it takes Tor to make the onion service live.

**Comment by unkaktus** [comment]
I think I will close this because of migration to new onion addresses (#40).
@ei8fdb, thanks for your insights! Many of them are still applicable to application as a whole. 🍻
